CREATE TABLE origem_ingresso
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_origem VARCHAR(31) NOT NULL,

    CONSTRAINT ck_origem_ingresso_tipo CHECK (
        tipo_origem IN ('CONVIDADO', 'ITEM_PEDIDO')
        )
);

INSERT INTO origem_ingresso (id, tipo_origem)
SELECT id, 'CONVIDADO' FROM convidado;

SELECT setval(
               pg_get_serial_sequence('origem_ingresso', 'id'),
               COALESCE((SELECT MAX(id) FROM origem_ingresso), 0) + 1,
               false
       );
ALTER TABLE convidado ALTER COLUMN id DROP IDENTITY IF EXISTS;

ALTER TABLE convidado
    ADD CONSTRAINT fk_convidado_origem_ingresso
        FOREIGN KEY (id) REFERENCES origem_ingresso (id) ON DELETE CASCADE;

CREATE TABLE tipo_ingresso
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    evento_id BIGINT       NOT NULL,
    nome      VARCHAR(255) NOT NULL,
    descricao TEXT,

    CONSTRAINT fk_tipo_ingresso_evento
        FOREIGN KEY (evento_id) REFERENCES evento (id) ON DELETE CASCADE
);

CREATE TABLE lote
(
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_ingresso_id   BIGINT         NOT NULL,
    numero_ordem       INTEGER        NOT NULL,
    preco              NUMERIC(10, 2) NOT NULL,
    qtd_total          INTEGER        NOT NULL,
    qtd_vendida        INTEGER        NOT NULL DEFAULT 0,
    data_inicio        TIMESTAMP,
    data_fim           TIMESTAMP,

    CONSTRAINT fk_lote_tipo_ingresso
        FOREIGN KEY (tipo_ingresso_id) REFERENCES tipo_ingresso (id) ON DELETE CASCADE,
    CONSTRAINT ck_lote_qtd_vendida_nao_excede CHECK (qtd_vendida <= qtd_total),
    CONSTRAINT ck_lote_quantidades_nao_negativas CHECK (qtd_total >= 0 AND qtd_vendida >= 0)
);

CREATE TABLE pedido
(
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT,
    nome_comprador     VARCHAR(255)   NOT NULL,
    email_comprador    VARCHAR(255)   NOT NULL,
    valor_total        NUMERIC(10, 2) NOT NULL,
    status_pedido      VARCHAR(20)    NOT NULL,
    data_criacao       TIMESTAMP      NOT NULL DEFAULT now(),
    data_expiracao     TIMESTAMP,
    gateway_referencia VARCHAR(255),

    CONSTRAINT fk_pedido_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL,
    CONSTRAINT ck_pedido_status CHECK (
        status_pedido IN ('PENDENTE', 'PAGO', 'CANCELADO', 'EXPIRADO', 'REEMBOLSADO')
        )
);

CREATE TABLE item_pedido
(
    id             BIGINT         NOT NULL PRIMARY KEY,
    pedido_id      BIGINT         NOT NULL,
    lote_id        BIGINT         NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,

    CONSTRAINT fk_item_pedido_origem_ingresso
        FOREIGN KEY (id) REFERENCES origem_ingresso (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_pedido_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedido (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_pedido_lote
        FOREIGN KEY (lote_id) REFERENCES lote (id) ON DELETE RESTRICT
);

ALTER TABLE ingressos ADD COLUMN origem_id BIGINT;

UPDATE ingressos SET origem_id = convidado_id;

ALTER TABLE ingressos ALTER COLUMN origem_id SET NOT NULL;

ALTER TABLE ingressos DROP CONSTRAINT fk_ingressos_convidado;
ALTER TABLE ingressos DROP COLUMN convidado_id;

ALTER TABLE ingressos
    ADD CONSTRAINT fk_ingressos_origem_ingresso
        FOREIGN KEY (origem_id) REFERENCES origem_ingresso (id) ON DELETE RESTRICT;

CREATE INDEX idx_tipo_ingresso_evento_id ON tipo_ingresso (evento_id);
CREATE INDEX idx_lote_tipo_ingresso_id ON lote (tipo_ingresso_id);
CREATE INDEX idx_pedido_usuario_id ON pedido (usuario_id);
CREATE INDEX idx_item_pedido_pedido_id ON item_pedido (pedido_id);
CREATE INDEX idx_item_pedido_lote_id ON item_pedido (lote_id);
CREATE INDEX idx_ingressos_origem_id ON ingressos (origem_id);